### Raiz
GET http://localhost:8080/api

### Criar usuário
POST http://localhost:8080/api/user HTTP/1.1
content-type: application/json

{
    "name": "Sófocles Teamildo",
    "email": "softeam@gmail.com",
    "password": "thecakeisalie"
}

### Obter todos os usuários
GET http://localhost:8080/api/user HTTP/1.1

### Obter um usuário pelo ID
GET http://localhost:8080/api/user/5f4d461db18acf384881fbba HTTP/1.1

### Atualizar dados do usuário
PUT http://localhost:8080/api/user/5f4e8cc5fe1b5b2340b6a1da HTTP/1.1
content-type: application/json

{
    "name": "Sófocles Teamildo Espírito Januário Cruz",
    "email": "softeamejc6@gmail.com",
    "password": "theprincessisinanothercastle"
}

### Deletar usuário
DELETE http://localhost:8080/api/user/5f51162b952ee025e87d0229 HTTP/1.1

### Autenticar
POST http://localhost:8080/api/auth HTTP/1.1
content-type: application/json

{
    "email": "softeam@gmail.com",
    "password": "thecakeisalie"
}

### Obter logs
GET http://localhost:8080/api/log