### Raiz
GET http://localhost:8080/api

### Criar usuário
POST http://localhost:8080/api/register HTTP/1.1
content-type: application/json

{
    "name": "Sófocles Teamildo",
    "email": "softeam@gmail.com",
    "password": "thecakeisalie"
}

### Obter todos os usuários
GET http://localhost:8080/api/user HTTP/1.1

### Obter um usuário pelo ID
GET http://localhost:8080/api/user/5f4d461db18acf384881fbba HTTP/1.1

### Atualizar dados do usuário
PUT http://localhost:8080/api/user/5f51234205dc3d1e2c613618 HTTP/1.1
content-type: application/json

{
    "name": "Sófocles Teamildo Espírito Januário Cruz",
    "email": "softeam@gmail.com",
    "password": "thecakeislie"
}

### Deletar usuário
DELETE http://localhost:8080/api/user/5f51193930cb910f4cf8e5ec HTTP/1.1

### Autenticar
POST http://localhost:8080/api/auth HTTP/1.1
content-type: application/json

{
    "email": "softeam@gmail.com",
    "password": "thecakeislie"
}

### Obter logs
GET http://localhost:8080/api/log